# Generated by Django 4.2.5 on 2023-10-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color_inside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет внутренний')),
            ],
        ),
        migrations.CreateModel(
            name='Color_outside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='', verbose_name='Фото')),
                ('door_id', models.IntegerField(verbose_name='Ид двери')),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('style', models.CharField(max_length=50, verbose_name='Стиль')),
                ('type_door', models.CharField(max_length=100, verbose_name='Тип')),
                ('properties', models.TextField(verbose_name='Характеристики')),
                ('description', models.TextField(verbose_name='Описание')),
                ('colors_inside', models.ManyToManyField(related_name='color_inside', to='main.color_inside')),
                ('colors_outside', models.ManyToManyField(related_name='color_inside', to='main.color_outside')),
                ('photos_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.photo_door')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': 'Двери',
            },
        ),
    ]
