# Generated by Django 4.2.5 on 2023-10-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photo_door_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='color_inside',
            name='code',
            field=models.CharField(default='000000', max_length=8, verbose_name='Код цвета'),
        ),
        migrations.AddField(
            model_name='color_outside',
            name='code',
            field=models.CharField(default='000000', max_length=8, verbose_name='Код цвета'),
        ),
    ]
