# Generated by Django 4.2.5 on 2023-10-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_color_inside_code_color_outside_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_door', models.CharField(max_length=100, verbose_name='Тип')),
            ],
        ),
        migrations.AlterField(
            model_name='door',
            name='type_door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_doors', to='main.type_door'),
        ),
    ]
