# Generated by Django 4.2.5 on 2023-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_door_type_door_door_type_doors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type_door',
            options={'verbose_name': 'Тип двери', 'verbose_name_plural': 'Типы дверей'},
        ),
    ]
