# Generated by Django 4.2.5 on 2023-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_type_door_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='type_doors',
        ),
        migrations.AddField(
            model_name='door',
            name='type_door',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='Type_door',
        ),
    ]
