# Generated by Django 4.2.5 on 2023-10-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_size_door_remove_door_style_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='sizes',
            new_name='Размер',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='type_doors',
            new_name='Тип',
        ),
    ]
