# Generated by Django 4.2.5 on 2023-10-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_sizes_door_размер_rename_type_doors_door_тип'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='Размер',
            field=models.ManyToManyField(related_name='size_doors', to='main.size_door'),
        ),
    ]
