# Generated by Django 4.2.5 on 2023-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_door_размер'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='Размер',
        ),
        migrations.AddField(
            model_name='door',
            name='sizes',
            field=models.ManyToManyField(null=True, related_name='size_doors', to='main.size_door'),
        ),
    ]
