# Generated by Django 4.2.5 on 2023-10-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_photo_door_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='Тип',
            new_name='type',
        ),
    ]
