# Generated by Django 4.2.6 on 2023-11-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_тип_door_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип двери',
                'verbose_name_plural': 'Типы дверей',
            },
        ),
        migrations.AlterModelOptions(
            name='type_door',
            options={},
        ),
        migrations.AddField(
            model_name='door',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category_door'),
        ),
    ]
