# Generated by Django 4.2.6 on 2023-11-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_door_sides_alter_door_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_door',
            name='link_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Назавание ссылки'),
        ),
    ]
