# Generated by Django 4.2.6 on 2023-11-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_category_door_link_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_door',
            options={'verbose_name': 'Ссылка и класс', 'verbose_name_plural': 'Ссылки и классы'},
        ),
    ]
